### ISSUE TITLE
Learn mode for number recognition

### ISSUE THREAD

**Issue by stevenortham** [iwatake2222/pico-mnist#1]
Hello there, so I got this working and it's amazing thanks for the great work! Some numbers work better than others and some things (like say the european way of writting 7 with horizontal bar in the middle) are not recognised. So I was wondering if it would be possible to add a learn or train mode so that you could write numbers and then indicate that number on the list to improve recognition. The same interface would work with a learn button, and maybe a reset to go back to the original settings. Just an idea, thanks!

**Comment by iwatake2222** [comment]
Thank you for the comment!
You can re-train the model using https://github.com/iwatake2222/pico-mnist/blob/master/pj_mnist/conv_mnist/tflmicro_mnist.ipynb with added data.
However, you need PC or cloud(like Google Colab) for it. Pico has too poor performance to train a model on it.
